services:
  postgres:
    image: postgres:15.3
    container_name: alphaca_alert_postgres
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      POSTGRES_DB: alphaca_alerts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
volumes:
  postgres_data: