"""add alpaca account and position snapshot tables

Revision ID: ff24ae658a54
Revises: 
Create Date: 2026-07-12 16:30:56.118480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from clickhouse_connect import cc_sqlalchemy
from clickhouse_connect.cc_sqlalchemy.datatypes.sqltypes import *  # noqa: F401,F403
from clickhouse_connect.cc_sqlalchemy.ddl.tableengine import *  # noqa: F401,F403

# revision identifiers, used by Alembic.
revision: str = 'ff24ae658a54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alpaca_account_snapshot',
    sa.Column('user_id', UUID, nullable=False),
    sa.Column('batched_at', DateTime64(3, 'UTC'), nullable=False),
    sa.Column('account_number', String, nullable=False),
    sa.Column('status', String, nullable=False),
    sa.Column('crypto_status', Nullable(String), ),
    sa.Column('currency', String, nullable=False),
    sa.Column('options_approved_level', Nullable(Int32), ),
    sa.Column('options_trading_level', Nullable(Int32), ),
    sa.Column('buying_power', Decimal(38, 10), nullable=False),
    sa.Column('regt_buying_power', Nullable(Decimal(38, 10)), ),
    sa.Column('daytrading_buying_power', Nullable(Decimal(38, 10)), ),
    sa.Column('effective_buying_power', Nullable(Decimal(38, 10)), ),
    sa.Column('non_marginable_buying_power', Nullable(Decimal(38, 10)), ),
    sa.Column('options_buying_power', Nullable(Decimal(38, 10)), ),
    sa.Column('bod_dtbp', Nullable(Decimal(38, 10)), ),
    sa.Column('cash', Decimal(38, 10), nullable=False),
    sa.Column('accrued_fees', Nullable(Decimal(38, 10)), ),
    sa.Column('pending_reg_taf_fees', Nullable(Decimal(38, 10)), ),
    sa.Column('intraday_adjustments', Nullable(Decimal(38, 10)), ),
    sa.Column('portfolio_value', Decimal(38, 10), nullable=False),
    sa.Column('equity', Decimal(38, 10), nullable=False),
    sa.Column('last_equity', Nullable(Decimal(38, 10)), ),
    sa.Column('long_market_value', Nullable(Decimal(38, 10)), ),
    sa.Column('short_market_value', Nullable(Decimal(38, 10)), ),
    sa.Column('position_market_value', Nullable(Decimal(38, 10)), ),
    sa.Column('initial_margin', Nullable(Decimal(38, 10)), ),
    sa.Column('maintenance_margin', Nullable(Decimal(38, 10)), ),
    sa.Column('last_maintenance_margin', Nullable(Decimal(38, 10)), ),
    sa.Column('sma', Nullable(Decimal(38, 10)), ),
    sa.Column('pattern_day_trader', Bool, nullable=False),
    sa.Column('trading_blocked', Bool, nullable=False),
    sa.Column('transfers_blocked', Bool, nullable=False),
    sa.Column('account_blocked', Bool, nullable=False),
    sa.Column('trade_suspended_by_user', Bool, nullable=False),
    sa.Column('shorting_enabled', Bool, nullable=False),
    sa.Column('multiplier', Nullable(String), ),
    sa.Column('daytrade_count', Int32, nullable=False),
    sa.Column('balance_asof', Nullable(Date), ),
    sa.Column('crypto_tier', Nullable(Int32), ),
    sa.PrimaryKeyConstraint('user_id', 'batched_at'),
    schema='landing_zone',
    clickhouse_engine=MergeTree(order_by=['user_id', 'batched_at'])
    )
    op.create_table('alpaca_position_snapshot',
    sa.Column('user_id', UUID, nullable=False),
    sa.Column('batched_at', DateTime64(3, 'UTC'), nullable=False),
    sa.Column('asset_id', UUID, nullable=False),
    sa.Column('symbol', String, nullable=False),
    sa.Column('exchange', String, nullable=False),
    sa.Column('asset_class', String, nullable=False),
    sa.Column('asset_marginable', Nullable(Bool), ),
    sa.Column('side', String, nullable=False),
    sa.Column('qty', Decimal(38, 10), nullable=False),
    sa.Column('qty_available', Decimal(38, 10), nullable=False),
    sa.Column('avg_entry_price', Decimal(38, 10), nullable=False),
    sa.Column('current_price', Nullable(Decimal(38, 10)), ),
    sa.Column('lastday_price', Nullable(Decimal(38, 10)), ),
    sa.Column('change_today', Nullable(Decimal(38, 10)), ),
    sa.Column('market_value', Nullable(Decimal(38, 10)), ),
    sa.Column('cost_basis', Nullable(Decimal(38, 10)), ),
    sa.Column('unrealized_pl', Nullable(Decimal(38, 10)), ),
    sa.Column('unrealized_plpc', Nullable(Decimal(38, 10)), ),
    sa.Column('unrealized_intraday_pl', Nullable(Decimal(38, 10)), ),
    sa.Column('unrealized_intraday_plpc', Nullable(Decimal(38, 10)), ),
    sa.PrimaryKeyConstraint('user_id', 'batched_at', 'asset_id'),
    schema='landing_zone',
    clickhouse_engine=MergeTree(order_by=['user_id', 'asset_id'])
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alpaca_position_snapshot',
    schema='landing_zone',
    clickhouse_engine=MergeTree(order_by=['user_id', 'asset_id']))
    op.drop_table('alpaca_account_snapshot',
    schema='landing_zone',
    clickhouse_engine=MergeTree(order_by=['user_id', 'batched_at']))
    # ### end Alembic commands ###
